sudo: required
language: node_js
cache: yarn
node_js:
  - 8
services:
  - docker
env:
  - NODE_PORT=3000
stages:
  - name: deploy
    if: (branch = master) AND (type != pull_request)

jobs:
  include:
    - stage: deploy
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin $DOCKER_IMG_HOST
        - docker build --rm=false -t $DOCKER_NAMESPACE/home-meter-monitor:$TRAVIS_BUILD_NUMBER .
        - docker tag $DOCKER_NAMESPACE/home-meter-monitor:$TRAVIS_BUILD_NUMBER $DOCKER_IMG_HOST/$DOCKER_NAMESPACE/home-meter-monitor:$TRAVIS_BUILD_NUMBER
        - docker tag $DOCKER_NAMESPACE/home-meter-monitor:$TRAVIS_BUILD_NUMBER $DOCKER_IMG_HOST/$DOCKER_NAMESPACE/home-meter-monitor:latest
        - docker push $DOCKER_IMG_HOST/$DOCKER_NAMESPACE/home-meter-monitor:$TRAVIS_BUILD_NUMBER
        - docker push $DOCKER_IMG_HOST/$DOCKER_NAMESPACE/home-meter-monitor:latest
notifications:
  email:
    recipients:
      - yhl@1024hw.cn
    on_success: never # default: change
    on_failure: always # default: always
